#version: "3.8"
#
#services:
#  redis:
#    image: redis:latest
#    container_name: redis_management_system
#    ports:
#      - "6379:6379"
#    restart: unless-stopped

version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_management_system
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres_management_system
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: leavemanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
